# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
# format code files with black
-   repo: local
    hooks:
    -   id: system
        name: Black
        entry: poetry run black
        types: ['python']
        language: system
# sort imports with isort
-   repo: local
    hooks:
    -   id: system
        name: isort
        entry: poetry run isort --profile black
        types: ['python']
        language: system
# run pylint against code base
-   repo: local
    hooks:
    -   id: system
        name: Pylint
        entry: poetry run pylint -j 0
        types: ['python']
        language: system
